In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('training_set_VU_DM_2014.csv')
data.head()

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,893,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,10404,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,21315,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,27348,2,4.0,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
4,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,29604,4,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

In [1]:
sampled = data.groupby(by='srch_id', as_index=False)
sampled.head()

NameError: name 'data' is not defined

In [2]:
import pandas as pd
data = pd.read_csv('training_set_VU_DM_2014.csv')
#data.head()
sampled = data.groupby(by='srch_id', as_index=False)
#sampled.head()

In [3]:
selected_names = np.random.choice(data.srch_id.unique(),5000,replace = False)
grouped = data[data.srch_id.isin(selected_names)]
#grouped.head()

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
selected_names = np.random.choice(data.srch_id.unique(),5000,replace = False)
grouped = data[data.srch_id.isin(selected_names)]
#grouped.head()

In [6]:
grouped.to_csv('5000users')
data = pd.read_csv('5000users')
data.head()

,Unnamed: 0,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,28,4,2012-12-31 08:59:22,5,219,NaN,NaN,219,3625,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
1,29,4,2012-12-31 08:59:22,5,219,NaN,NaN,219,11622,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
2,30,4,2012-12-31 08:59:22,5,219,NaN,NaN,219,11826,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
3,31,4,2012-12-31 08:59:22,5,219,NaN,NaN,219,22824,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
4,32,4,2012-12-31 08:59:22,5,219,NaN,NaN,219,37581,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [7]:
import numpy as np
import pandas as pd
from scipy import stats, integrate
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
np.random.seed(sum(map(ord, "distributions")))

In [8]:
posdata = data.groupby('position')

In [9]:

labels = range(1, 40)

In [10]:
sns.distplot(posdata)

TypeError: Could not operate 1 with block values unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
w