In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('ODI-2018.csv')

In [4]:
dataset

,Timestamp,prog,ml,ir,stat,db,gender,choco,birth,neigh,stand,dm,rand,time,gd1,gd2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04/05/2018 11:22,Duisenberg Quantitative Risk Management,no,0,mu,nee,male,neither,10/12/1994,49000,no,0.05,7,1,Productive,Good sleep
2,04/05/2018 11:23,Computer Science,no,0,unknown,ja,male,I have no idea what you are talking about,06/08/1993,100,yes,The formmer,394749,1 a m,got a 8.5,got 2 8.5s
3,04/05/2018 11:23,Business Analytics,yes,1,sigma,ja,male,neither,25-Dec-92,5,no,Not enough,6,23,Food,Sport
4,04/05/2018 11:23,BA,yes,1,mu,ja,male,I have no idea what you are talking about,01/02/1995,2,no,0,8,0.3,-,-
5,04/05/2018 11:23,Master Computer Science: Big Data Engineering,no,0,sigma,ja,male,I have no idea what you are talking about,09.01.1994,6,no,0,8,00:00,sleep,beer
6,04/05/2018 11:24,Drug discovery and safety,no,0,mu,nee,male,fat,17/08/1994,4,no,100,No,09:00,Chocolate,Doing nothing
7,04/05/2018 11:25,CS,yes,1,mu,nee,male,neither,27/09/1993,5,no,£1,6739,2300,Chocolate,More chocolate
8,04/05/2018 11:25,Computational Science,no,0,mu,ja,male,fat,14-May-94,5,yes,0.25,3,12,Sunshine,Friends
9,04/05/2018 11:25,M Financial Economtrics,no,0,mu,nee,male,neither,11/04/1931,2,no,"0,25 pond",78952097,1:00 AM,Sun,Rain
10,04/05/2018 11:25,MSc Bioinformatics and Systems Biology,yes,1,unknown,ja,male,slim,19/08/1993,7,no,0.3,5,02:00,Free time,More free time
11,04/05/2018 11:25,Econometrics,no,0,mu,nee,female,I have no idea what you are talking about,16/05/1990,8,yes,0.003,8,00:00,Good coffee,Sunshine
12,04/05/2018 11:26,CS,no,0,mu,ja,female,slim,30/03/1995,6,no,1,42,23.45,Cats,Coffee
13,04/05/2018 11:26,Bioinformatics,yes,0,mu,nee,female,fat,Oct-16,8,no,2,37,0.3,Sunny weather,Good food
14,04/05/2018 11:26,AI,yes,1,sigma,ja,male,I have no idea what you are talking about,this year,6,no,more,7727528,01:00,Good grades,All grades
15,04/05/2018 11:26,EOR,yes,0,mu,nee,male,I have no idea what you are talking about,02-Apr,2,no,99,187,8,Food,Wine
16,04/05/2018 11:26,Bioinformatics,no,0,mu,nee,female,fat,05/02/1994,1,no,0.25,7,23:30,Pancakes for breakfast,No wind
17,04/05/2018 11:26,BA,yes,1,mu,ja,female,I have no idea what you are talking about,22-Jan,1,yes,100,7,01:30,Sleep,Netflix
18,04/05/2018 11:26,BA,yes,1,mu,ja,male,fat,07/10/1994,3,no,80,6,01:00,Sleep,Relax
19,04/05/2018 11:26,AI,yes,1,mu,ja,female,fat,23/02/1995,2,no,"0,50",34,23:30,Good sleep,Go to the gym
20,04/05/2018 11:26,CS,no,0,mu,ja,male,neither,24/03/1994,1,no,1,7,I didn't,Pizza,Beer
21,04/05/2018 11:27,Computational Science,no,0,mu,nee,male,I have no idea what you are talking about,04/01/1996,7,unknown,100/N,6.28E+36,23:59,Pancakes,Pizza
22,04/05/2018 11:27,Big Data Engineering,yes,0,mu,ja,male,I have no idea what you are talking about,07/12/1995,2,no,£200,2,23:20,Good foodd,Lot of foodd
23,04/05/2018 11:27,AI,yes,1,mu,nee,male,I have no idea what you are talking about,04.11.1992,1,no,70,2,2 a.m.,sex,good food
24,04/05/2018 11:27,AI,no,0,mu,nee,female,I have no idea what you are talking about,05/11/1993,5,no,",50",6,23:30,Puppies,sunshine
25,04/05/2018 11:27,Computational Science,no,0,mu,nee,female,neither,03-Nov,8,no,0.25,7,23.3,Nice grades,Good food
26,04/05/2018 11:27,MSc Computer Science,no,0,mu,ja,male,fat,21/09/1994,8,unknown,10,4,01:30,Coffee,Good night sleep
27,04/05/2018 11:27,BA,yes,1,mu,nee,male,slim,19-Oct,2,no,110,Hoi,23:30,Cheese,Beer
28,04/05/2018 11:27,Business Analytics,yes,1,mu,nee,female,fat,14-Apr,2,no,10,9,22.2,Coffee,Food
29,04/05/2018 11:27,AI,yes,1,mu,ja,male,fat,23-Dec,5,no,1234,4,23:30,Food,Coffee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,04/05/2018 11:28,Artificial intelligence,no,unknown,mu,unknown,female,neither,25/08/1996,0,no,1euro,3,0,Food,Not having Anything to do
189,04/05/2018 11:28,BA,yes,0,mu,nee,male,fat,07/07/1992,3,no,5,4,01:30,Sleep,Sports
190,04/05/2018 11:28,Masters Computer Science(big data engineering),no,1,mu,ja,male,I have no idea what you are talking about,02/04/1995,6,no,100/n,9,12,Cloudy skies,Memes
191,04/05/2018 11:28,Computational Science,yes,0,mu,nee,male,neither,17-Nov,3,no,1,10,01:00,afternoon lectures,weekend
192,04/05/2018 11:28,BA,yes,0,mu,nee,male,fat,01/09/1994,3,yes,200,1,00:00,Food,No college
193,04/05/2018 11:28,BA,yes,1,mu,ja,female,fat,23/02/1995,5,no,30,9,23:30,Getting a good grade,Sleep well
194,04/05/2018 11:28,Econometrics,no,0,mu,unknown,male,fat,02/09/1993,1,no,0.25,2,00:30,nice weather,fun time
195,04/05/2018 11:28,Computational Science,yes,0,mu,nee,male,I have no idea what you are talking about,07/06/1993,4,yes,"0,33",42,23:15,No lecture at 9,No lectures
196,04/05/2018 11:28,Computer Science,yes,1,mu,ja,male,fat,01-Dec,5,no,0.4,69,02:30,Morning sex,Going to the gym
197,04/05/2018 11:28,Business Analytics,yes,0,mu,ja,female,neither,19/03/1993,4,no,100/300,9,00:00,Good sleep,Free time
198,04/05/2018 11:28,Bioinformatics master,yes,0,sigma,nee,female,neither,?,04-Aug,no,5,8,22:00,good weather,Achievement
199,04/05/2018 11:28,Mathematics,no,0,mu,nee,female,I have no idea what you are talking about,24/09/1996,7,no,5,7,23:00,A good sleep,Be around nice people
200,04/05/2018 11:28,Bioinformatics and Systems biology,no,0,mu,ja,male,I have no idea what you are talking about,02/05/1996,7,no,3,3,12,Good night rest,No compile errors on first try
201,04/05/2018 11:28,OR,no,0,mu,nee,male,neither,1995,3,no,10,ACHT,0,Sports,Chocolate
202,04/05/2018 11:28,Computational Science,yes,unknown,mu,ja,male,neither,1990,1,no,80,4,300,productivity,no pain
203,04/05/2018 11:28,Bioinformatics & Systems Biology,no,0,mu,nee,male,fat,26/11/1993,1,no,5,382763,23,Good sleep,Cheese
204,04/05/2018 11:28,AI,yes,0,mu,ja,male,fat,18/08/1994,1,no,20,7,23:00,Coffee,Music
205,04/05/2018 11:28,AI VU,no,0,mu,nee,male,fat,30/12/1990,5,no,50,6,3am,Good sleep,Sports
206,04/05/2018 11:28,Computational Science,yes,0,sigma,nee,male,neither,August 7th,2,no,0,4,04:30,1,2
207,04/05/2018 11:28,Business Analytics,yes,1,sigma,ja,male,unknown,05/04/2000,400,unknown,1.00E+24,7,04:00,Guest lecture by Tupac,0 heart attacks
208,04/05/2018 11:28,Cls,no,0,sigma,nee,male,slim,25/12/1991,7,no,0.34,7,02:00,Temptation Island,Sun
209,04/05/2018 11:28,QRM,no,0,mu,ja,male,I have no idea what you are talking about,18-Mar,1,no,5,3,0,"Sunshine, structure","Following 4 courses at the same time, rain"
210,04/05/2018 11:29,MSc Bioinformatics and Systems Biology,yes,0,mu,nee,female,neither,24/10/1993,1,no,£.25,5,01:05,A good book,Nice people
211,04/05/2018 11:29,Ai,yes,1,mu,ja,male,I have no idea what you are talking about,09/02/1993,6,no,50,9,3 3,Hanging out,Sex
212,04/05/2018 11:30,Artificial Intelligence,no,0,mu,nee,male,slim,09-Nov,2,unknown,0.50 euros,6123,23.3,food,friends
213,04/05/2018 11:38,Econometrics,no,0,mu,nee,male,fat,22/11/1991,3,no,2,2,2:00 AM,Freedom,Money
214,04/05/2018 12:10,AI,no,0,unknown,unknown,female,neither,20/05/1993,7,unknown,0,88,22.47,Sun,Activities
215,04/05/2018 13:15,AI,yes,1,mu,nee,male,fat,30/07/1992,8,no,11,2,04:00,The foresight of a night out with friends,The taste of that first sip of cold beer on a ...
216,04/05/2018 15:09,Physics,no,1,mu,nee,male,neither,04/12/1991,5,no,about 0.4£ for N=250,10,01:30,Good company,Well rested and structured
217,04/05/2018 18:04,BA,yes,1,mu,ja,male,fat,07/10/1994,3,no,80,6,01:00,Sleep,Relax

In [5]:
data['rand']

NameError: name 'data' is not defined

In [17]:
data.dropna(subset=['rand'])

,Timestamp,prog,Have you taken a course on machine learning?,Have you taken a course on information retrieval?,Have you taken a course on statistics?,Have you taken a course on databases?,What is your gender?,Chocolate makes you.....,When is your birthday (date)?,Number of neighbors sitting around you?,Did you stand up?,"You can get £100 if you win a local DM competition, or we don’t hold any competitions and I give everyone some money (not the same amount!). How much do you think you would get then?",rand,Time you went to be Yesterday,What makes a good day for you (1)?,What makes a good day for you (2)?
1,04/05/2018 11:22,Duisenberg Quantitative Risk Management,no,0,mu,nee,male,neither,10/12/1994,49000,no,0.05,7,1,Productive,Good sleep
2,04/05/2018 11:23,Computer Science,no,0,unknown,ja,male,I have no idea what you are talking about,06/08/1993,100,yes,The formmer,394749,1 a m,got a 8.5,got 2 8.5s
3,04/05/2018 11:23,Business Analytics,yes,1,sigma,ja,male,neither,25-Dec-92,5,no,Not enough,6,23,Food,Sport
4,04/05/2018 11:23,BA,yes,1,mu,ja,male,I have no idea what you are talking about,01/02/1995,2,no,0,8,0.3,-,-
5,04/05/2018 11:23,Master Computer Science: Big Data Engineering,no,0,sigma,ja,male,I have no idea what you are talking about,09.01.1994,6,no,0,8,00:00,sleep,beer
6,04/05/2018 11:24,Drug discovery and safety,no,0,mu,nee,male,fat,17/08/1994,4,no,100,No,09:00,Chocolate,Doing nothing
7,04/05/2018 11:25,CS,yes,1,mu,nee,male,neither,27/09/1993,5,no,£1,6739,2300,Chocolate,More chocolate
8,04/05/2018 11:25,Computational Science,no,0,mu,ja,male,fat,14-May-94,5,yes,0.25,3,12,Sunshine,Friends
9,04/05/2018 11:25,M Financial Economtrics,no,0,mu,nee,male,neither,11/04/1931,2,no,"0,25 pond",78952097,1:00 AM,Sun,Rain
10,04/05/2018 11:25,MSc Bioinformatics and Systems Biology,yes,1,unknown,ja,male,slim,19/08/1993,7,no,0.3,5,02:00,Free time,More free time
11,04/05/2018 11:25,Econometrics,no,0,mu,nee,female,I have no idea what you are talking about,16/05/1990,8,yes,0.003,8,00:00,Good coffee,Sunshine
12,04/05/2018 11:26,CS,no,0,mu,ja,female,slim,30/03/1995,6,no,1,42,23.45,Cats,Coffee
13,04/05/2018 11:26,Bioinformatics,yes,0,mu,nee,female,fat,Oct-16,8,no,2,37,0.3,Sunny weather,Good food
14,04/05/2018 11:26,AI,yes,1,sigma,ja,male,I have no idea what you are talking about,this year,6,no,more,7727528,01:00,Good grades,All grades
15,04/05/2018 11:26,EOR,yes,0,mu,nee,male,I have no idea what you are talking about,02-Apr,2,no,99,187,8,Food,Wine
16,04/05/2018 11:26,Bioinformatics,no,0,mu,nee,female,fat,05/02/1994,1,no,0.25,7,23:30,Pancakes for breakfast,No wind
17,04/05/2018 11:26,BA,yes,1,mu,ja,female,I have no idea what you are talking about,22-Jan,1,yes,100,7,01:30,Sleep,Netflix
18,04/05/2018 11:26,BA,yes,1,mu,ja,male,fat,07/10/1994,3,no,80,6,01:00,Sleep,Relax
19,04/05/2018 11:26,AI,yes,1,mu,ja,female,fat,23/02/1995,2,no,"0,50",34,23:30,Good sleep,Go to the gym
20,04/05/2018 11:26,CS,no,0,mu,ja,male,neither,24/03/1994,1,no,1,7,I didn't,Pizza,Beer
21,04/05/2018 11:27,Computational Science,no,0,mu,nee,male,I have no idea what you are talking about,04/01/1996,7,unknown,100/N,6.28395E+36,23:59,Pancakes,Pizza
22,04/05/2018 11:27,Big Data Engineering,yes,0,mu,ja,male,I have no idea what you are talking about,07/12/1995,2,no,£200,2,23:20,Good foodd,Lot of foodd
23,04/05/2018 11:27,AI,yes,1,mu,nee,male,I have no idea what you are talking about,04.11.1992,1,no,70,2,2 a.m.,sex,good food
24,04/05/2018 11:27,AI,no,0,mu,nee,female,I have no idea what you are talking about,05/11/1993,5,no,",50",6,23:30,Puppies,sunshine
25,04/05/2018 11:27,Computational Science,no,0,mu,nee,female,neither,03-Nov,8,no,0.25,7,23.3,Nice grades,Good food
26,04/05/2018 11:27,MSc Computer Science,no,0,mu,ja,male,fat,21/09/1994,8,unknown,10,4,01:30,Coffee,Good night sleep
27,04/05/2018 11:27,BA,yes,1,mu,nee,male,slim,19-Oct,2,no,110,Hoi,23:30,Cheese,Beer
28,04/05/2018 11:27,Business Analytics,yes,1,mu,nee,female,fat,14-Apr,2,no,10,9,22.2,Coffee,Food
29,04/05/2018 11:27,AI,yes,1,mu,ja,male,fat,23-Dec,5,no,1234,4,23:30,Food,Coffee
30,04/05/2018 11:27,Econometrics,no,0,mu,nee,female,fat,29/10/1991,1,no,01-Apr,3,01:20,Good food,Lovely people
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,04/05/2018 11:28,Artificial intelligence,no,unknown,mu,unknown,female,neither,25/08/1996,0,no,1euro,3,0,Food,Not having Anything to do
189,04/05/2018 11:28,BA,yes,0,mu,nee,male,fat,07/07/1992,3,no,5,4,01:30,Sleep,Sports
190,04/05/2018 11:28,Masters Computer Science(big data engineering),no,1,mu,ja,male,I have no idea what you are talking about,02/04/1995,6,no,100/n,9,12,Cloudy skies,Memes
191,04/05/2018 11:28,Computational Science,yes,0,mu,nee,male,neither,17-Nov,3,no,1,10,01:00,afternoon lectures,weekend
192,04/05/2018 11:28,BA,yes,0,mu,nee,male,fat,01/09/1994,3,yes,200,1,00:00,Food,No college
193,04/05/2018 11:28,BA,yes,1,mu,ja,female,fat,23/02/1995,5,no,30,9,23:30,Getting a good grade,Sleep well
194,04/05/2018 11:28,Econometrics,no,0,mu,unknown,male,fat,02/09/1993,1,no,0.25,2,00:30,nice weather,fun time
195,04/05/2018 11:28,Computational Science,yes,0,mu,nee,male,I have no idea what you are talking about,07/06/1993,4,yes,"0,33",42,23:15,No lecture at 9,No lectures
196,04/05/2018 11:28,Computer Science,yes,1,mu,ja,male,fat,01-Dec,5,no,0.4,69,02:30,Morning sex,Going to the gym
197,04/05/2018 11:28,Business Analytics,yes,0,mu,ja,female,neither,19/03/1993,4,no,100/300,9,00:00,Good sleep,Free time
198,04/05/2018 11:28,Bioinformatics master,yes,0,sigma,nee,female,neither,?,04-Aug,no,5,8,22:00,good weather,Achievement
199,04/05/2018 11:28,Mathematics,no,0,mu,nee,female,I have no idea what you are talking about,24/09/1996,7,no,5,7,23:00,A good sleep,Be around nice people
200,04/05/2018 11:28,Bioinformatics and Systems biology,no,0,mu,ja,male,I have no idea what you are talking about,02/05/1996,7,no,3,3,12,Good night rest,No compile errors on first try
201,04/05/2018 11:28,OR,no,0,mu,nee,male,neither,1995,3,no,10,ACHT,0,Sports,Chocolate
202,04/05/2018 11:28,Computational Science,yes,unknown,mu,ja,male,neither,1990,1,no,80,4,300,productivity,no pain
203,04/05/2018 11:28,Bioinformatics & Systems Biology,no,0,mu,nee,male,fat,26/11/1993,1,no,5,382763,23,Good sleep,Cheese
204,04/05/2018 11:28,AI,yes,0,mu,ja,male,fat,18/08/1994,1,no,20,7,23:00,Coffee,Music
205,04/05/2018 11:28,AI VU,no,0,mu,nee,male,fat,30/12/1990,5,no,50,6,3am,Good sleep,Sports
206,04/05/2018 11:28,Computational Science,yes,0,sigma,nee,male,neither,August 7th,2,no,0,4,04:30,1,2
207,04/05/2018 11:28,Business Analytics,yes,1,sigma,ja,male,unknown,05/04/2000,400,unknown,1.00E+24,7,04:00,Guest lecture by Tupac,0 heart attacks
208,04/05/2018 11:28,Cls,no,0,sigma,nee,male,slim,25/12/1991,7,no,0.34,7,02:00,Temptation Island,Sun
209,04/05/2018 11:28,QRM,no,0,mu,ja,male,I have no idea what you are talking about,18-Mar,1,no,5,3,0,"Sunshine, structure","Following 4 courses at the same time, rain"
210,04/05/2018 11:29,MSc Bioinformatics and Systems Biology,yes,0,mu,nee,female,neither,24/10/1993,1,no,£.25,5,01:05,A good book,Nice people
211,04/05/2018 11:29,Ai,yes,1,mu,ja,male,I have no idea what you are talking about,09/02/1993,6,no,50,9,3 3,Hanging out,Sex
212,04/05/2018 11:30,Artificial Intelligence,no,0,mu,nee,male,slim,09-Nov,2,unknown,0.50 euros,6123,23.3,food,friends
213,04/05/2018 11:38,Econometrics,no,0,mu,nee,male,fat,22/11/1991,3,no,2,2,2:00 AM,Freedom,Money
214,04/05/2018 12:10,AI,no,0,unknown,unknown,female,neither,20/05/1993,7,unknown,0,88,22.47,Sun,Activities
215,04/05/2018 13:15,AI,yes,1,mu,nee,male,fat,30/07/1992,8,no,11,2,04:00,The foresight of a night out with friends,The taste of that first sip of cold beer on a ...
216,04/05/2018 15:09,Physics,no,1,mu,nee,male,neither,04/12/1991,5,no,about 0.4£ for N=250,10,01:30,Good company,Well rested and structured
217,04/05/2018 18:04,BA,yes,1,mu,ja,male,fat,07/10/1994,3,no,80,6,01:00,Sleep,Relax

In [25]:
data['rand'].dropna()

1                7
2           394749
3                6
4                8
5                8
6               No
7             6739
8                3
9         78952097
10               5
11               8
12              42
13              37
14         7727528
15             187
16               7
17               7
18               6
19              34
20               7
21     6.28395E+36
22               2
23               2
24               6
25               7
26               4
27             Hoi
28               9
29               4
30               3
          ...
188              3
189              4
190              9
191             10
192              1
193              9
194              2
195             42
196             69
197              9
198              8
199              7
200              3
201           ACHT
202              4
203         382763
204              7
205              6
206              4
207              7
208              7
209              3
210              5
211              9
212           6123
213              2
214             88
215              2
216             10
217              6
Name: rand, Length: 217, dtype: object

In [30]:
pd.to_numeric(data['rand'], errors='drop')
data['rand'].dropna()

1                7
2           394749
3                6
4                8
5                8
6               No
7             6739
8                3
9         78952097
10               5
11               8
12              42
13              37
14         7727528
15             187
16               7
17               7
18               6
19              34
20               7
21     6.28395E+36
22               2
23               2
24               6
25               7
26               4
27             Hoi
28               9
29               4
30               3
          ...
188              3
189              4
190              9
191             10
192              1
193              9
194              2
195             42
196             69
197              9
198              8
199              7
200              3
201           ACHT
202              4
203         382763
204              7
205              6
206              4
207              7
208              7
209              3
210              5
211              9
212           6123
213              2
214             88
215              2
216             10
217              6
Name: rand, Length: 217, dtype: object

In [ ]:
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install seaborn

import seaborn as sns

In [ ]:
sns.distplot(data['rand']);

In [40]:
dataset.cov()

Empty DataFrame
Columns: []
Index: []